### ISSUE TITLE
连接不上hbasea

### ISSUE THREAD

**Issue by wqstc1213110** [Observe-secretly/HbaseGUI#1]
cmd界面提示 初始化Hbase链接，然后就卡死不动了

**Comment by Observe-secretly** [comment]
这多半是你所在的网络环境无法链接Hbase导致的。请确保两个关键信息一定正确并可用的。
1、ZK地址是否可以正常访问。请使用telnet 命令尝试访问ZK的2181（通常ZK端口就是2181，请以实际为准）端口；
2、请确认你在登录时填写的ZNODE.PARENT是正确的。你可以在Hbase Master GUI上看到此信息
