### ISSUE TITLE
下载驱动报错了

### ISSUE THREAD

**Issue by youxuehu** [Observe-secretly/HbaseGUI#10]
![image](https://user-images.githubusercontent.com/36439780/75743564-500abc80-5d4c-11ea-8797-abefb5ba7064.png)

![image](https://user-images.githubusercontent.com/36439780/75743572-5ac55180-5d4c-11ea-9b10-284e482048ab.png)

**Comment by Observe-secretly** [comment]
感谢反馈。问题已修复。请下载V 1.2.2 版本。关于驱动包我已经提供了离线下载的方式。请移步 https://github.com/Observe-secretly/HbaseGUI/wiki/Release-history
