### ISSUE TITLE
阿里云serverless版本的支持吗？

### ISSUE THREAD

**Issue by hugetiny** [Observe-secretly/HbaseGUI#12]
貌似只能通过外网链接连接
没其他什么参数

**Comment by hugetiny** [comment]
与HBase标准版提供Zookeeper集群地址做为访问地址不同的是，HBase Serverless版使用一个地址域名作为访问的统一入口，该地址域名背后是一组高可用的服务器，能够帮助HBase客户端与后端的RegionServer建立直连，以进行高性能地访问。

**Comment by Observe-secretly** [comment]
你好，阿里云的这款产品我们没有使用过。你可能需要自己研究下
