### ISSUE TITLE
您好，最新的1.2.1版本我连接数据库提示这个，maven编译是成功的，驱动也拷贝到了conf

### ISSUE THREAD

**Issue by FreshCoderKimi** [Observe-secretly/HbaseGUI#13]
![image](https://user-images.githubusercontent.com/22710771/79420079-bab94400-7fea-11ea-825c-40f8ada3fbd5.png)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.231 s
[INFO] Finished at: 2020-04-16T13:59:20+08:00
[INFO] ------------------------------------------------------------------------
download dependency jar success
download adapter jar ....ok
[mg01.cechealth.cn,mg02.cechealth.cn,mg03.cechealth.cn](http://mg01.cechealth.cn)
初始化Hbase链接...
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[mg01.cechealth.cn,mg02.cechealth.cn,mg03.cechealth.cn](http://mg01.cechealth.cn)
初始化Hbase链接...

**Comment by FreshCoderKimi** [comment]
删掉了Mac 用户目录下自动生成的.hbase-gui-conf下的驱动，然后按照说明在conf下解压离线驱动解决了

**Comment by perkinls** [comment]
你好，请问怎么能联系上你
