### ISSUE TITLE
只支持1.3.2版本的hbase？

### ISSUE THREAD

**Issue by powerLeePlus** [Observe-secretly/HbaseGUI#14]
hbase version下拉菜单里最高只有1.3.2
![image](https://user-images.githubusercontent.com/25865085/79822290-5cfa7280-83c3-11ea-877f-9cd477d3d050.png)

1.3.2也提示没有Adapater
![image](https://user-images.githubusercontent.com/25865085/79822330-7d2a3180-83c3-11ea-96e1-fa154f38386b.png)

**Comment by Observe-secretly** [comment]
感谢反馈。我这几天会把2.x的Hbase社区版本适配上去。关于HbaseAdapter缺失的问题，请在wiki中找到离线包下载。因为在线下载的资源是从GitHub上获取的。它可能不是特别稳定。请使用离线包

**Comment by feipengcheng** [comment]
我用的1.3.6  居然没有

**Comment by Observe-secretly** [comment]
@feipengcheng  如果你的Hbase是1.x版本，通常你选择1.x.x的任意版本，都不会出现问题。如果遇到问题提issues

**Comment by Observe-secretly** [comment]
@powerLeePlus 现已经支持Hbase2.x的社区版本。请下载最新版本的软件和驱动（最新版本的驱动有功能增强，它不适配之前的软件）。
