### ISSUE TITLE
下载依赖会遇到一个异常

### ISSUE THREAD

**Issue by datagic** [Observe-secretly/HbaseGUI#27]
各版本下载依赖会开始的时候都会遇到这个报错，导致失败。请问是我漏掉了哪个步骤吗？
<img width="847" alt="image" src="https://user-images.githubusercontent.com/23647070/193021778-61419187-67f8-4d59-840e-ea2b19ec0919.png">

**Comment by Observe-secretly** [comment]
在文档中下载离线包即可。在线依赖可能需要vpn才能正常下载
