### ISSUE TITLE
win10运行run.bat 会闪一下，打不开

### ISSUE THREAD

**Issue by Invalid-oath** [Observe-secretly/HbaseGUI#3]

**Comment by Observe-secretly** [comment]
我真的非常抱歉。我使用的是Mac电脑开发测试的。软件也会在Windows上测试（Win10也测试过）。但是并没有你说的闪退情况。我建议你在命令行手动执行start.bat 然后把错误信息贴出来，这样我可能会更加明确你所遇到的问题。如果你有java开发经验就更好了。请注意作者是在jdk8下开发的

**Comment by Invalid-oath** [comment]
你好！
            非常抱歉，后面我解决了，软件没有问题。在命令行启动发现错误原因为jdk路径不对，修改过路径就OK了。不好意思哈~，忘记更新评论了。



949666270@qq.com
 
发件人： 李民
发送时间： 2019-10-15 01:38
收件人： Observe-secretly/HbaseGUI
抄送： Invalid-oath; Author
主题： Re: [Observe-secretly/HbaseGUI] win10运行run.bat 会闪一下，打不开 (#3)
我真的非常抱歉。我使用的是Mac电脑开发测试的。软件也会在Windows上测试（Win10也测试过）。但是并没有你说的闪退情况。我建议你在命令行手动执行start.bat 然后把错误信息贴出来，这样我可能会更加明确你所遇到的问题。如果你有java开发经验就更好了。请注意作者是在jdk8下开发的
―
