### ISSUE TITLE
下载的jar文件太多了，建议优化一下pom文件，去除不必要的依赖

### ISSUE THREAD

**Issue by qiankeqin** [Observe-secretly/HbaseGUI#4]
下载的jar文件太多了，建议优化一下pom文件，去除不必要的依赖

**Comment by Observe-secretly** [comment]
软件本身没有太多依赖。你说的jar文件太多指的是你在选择hbase版本的时候自动下载的jar包吗？这是访问Habse所必须的jar包。我也希望可以像mysql驱动一样只有一个该多好。
