### ISSUE TITLE
如果想推广，请先写操作手册

### ISSUE THREAD

**Issue by quanwei132** [Observe-secretly/HbaseGUI#8]
如果想推广，请先写操作手册
你理解不是别人理解你的意思。

各个参数填什么，搞了半天没有搞定。连个截图参考都美哦与

**Comment by Junvn** [comment]
说真的hbase这方面的可视化工具真的少，有些老的也没人维护了，结合phoenix用dbeaver来玩不知道效果怎么样

**Comment by Observe-secretly** [comment]
有图文介绍的。可能因为网络的原因或者其他更多原因导致图片显示有问题。如果你尝试多次仍然无法 查看图片，请在HbaseGUI/README_IMAGE/  里面打开图片查看。里面包含软件的图文介绍；我意识到这个问题确实比较麻烦。后面会把它（图片）资源放在其他地方。

**Comment by MakTaiSong** [comment]
作为一个测试，我完全不知道填啥，作者写一下手册吧，不是每一个都熟悉hbase的

**Comment by Observe-secretly** [comment]
测试是如果不懂hbase确实很难知道这些参数如何填写。详细的操作手册，回头我写在国内的站点上面放在README上供大家查阅

**Comment by RenYueHD** [comment]
真的不知道怎么用,一头雾水
